### ISSUE TITLE
Login not possible in Windows app 8.2.0

### ISSUE THREAD

**Issue by omicron81** [toggl/track-windows-feedback#26]
**Describe the bug**
After installing 8.2.0 Windows app, the login does not work. Neither Google nor email login. "Sorry, we're having trouble logging you in. Please try again."

**Steps to reproduce**
1. Click on "continue with Google" button. Browser opens (Brave)
2. Select google account, that has been used successfully to login to toggl website and old windows app. -> Browser shows message "Received verification code. You may now close this window."
3. Go back to toggl track app. Error message is displayed on login form: "Sorry, we're having trouble logging you in. Please try again."
4. E-Mail login: Enter registered email address and password. Click "Sign in with email" -> Shows the same error message: "Sorry, we're having trouble logging you in. Please try again."

**Expected behavior**
Successful login to toggl track. The same as it works in the old windows app and on the website

**Screenshots**
![image](https://user-images.githubusercontent.com/8233992/214034571-e3c0ede4-85b8-444c-b155-1fc319ba63e8.png)

**Environment (please complete the following information):**
Windows 10 21H2, no proxy

**Additional context**
toggl track windows version 8.2.0
Login works fine using the old app 7.5.454

**Comment by kornelijepetak** [comment]
@omicron81 for some reason, the login does not work for a very small percentage of the users, so please contact our customer support (by email or via Send Feedback within the app) and they'll try to help you as best as they can. This will help us determine why exactly the login does not work correctly for you.

**Comment by kornelijepetak** [comment]
📢 Some of the detected issues with the login were solved in more recent versions of Toggl Track. Please update to the latest version!

⛔ If you encounter more issues, please contact customer support or open this issue again with a comment!

**Comment by omicron81** [comment]
@kornelijepetak I've Updated to version 8.2.3, but the issue is still the same.
Neither Google login nor login via email address works. I have attached the log file ([log20230217.txt](https://github.com/toggl/track-windows-feedback/files/10766227/log20230217.txt))

The exception:
```  ---> System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: The read operation failed, see inner exception.
 ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (0x80090326): Das Format der empfangenen Nachricht war unerwartet oder fehlerhaft.
```

**Comment by omicron81** [comment]
OpenVPN is installed, but not connected. I turned off SSL verification, restarted the app, but the same error message / log messages persist.

I've checked the URL from the logs (https://desktop.track.toggl.com/api/v9/me) with Edge and Firefox. With both, I get response 418 (Teapot), but 

- Firefox displays the connection as secure (Verified by Google Trust Services LLC)
- Edge displays the connection as insecure. But I'm not sure if this is because of the shown error page

In PowerShell:
```
PS C:\> Invoke-WebRequest https://desktop.track.toggl.com/api/v9/me
Invoke-WebRequest : Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
In Zeile:1 Zeichen:1
+ Invoke-WebRequest https://desktop.track.toggl.com/api/v9/me
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
```

WLS Ubuntu:
```
$ curl https://desktop.track.toggl.com/api/v9/me -v
*   Trying 34.120.83.142:443...
* TCP_NODELAY set
* Connected to desktop.track.toggl.com (34.120.83.142) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use h2
* Server certificate:
*  subject: CN=desktop.track.toggl.com
*  start date: Jan 30 21:50:35 2023 GMT
*  expire date: Apr 30 22:43:38 2023 GMT
*  subjectAltName: host "desktop.track.toggl.com" matched cert's "desktop.track.toggl.com"
*  issuer: C=US; O=Google Trust Services LLC; CN=GTS CA 1D4
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x557fd04158e0)
> GET /api/v9/me HTTP/2
> Host: desktop.track.toggl.com
> user-agent: curl/7.68.0
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 418
< server: nginx
< date: Fri, 17 Feb 2023 14:14:55 GMT
< content-length: 0
< instance: time-desktop
< strict-transport-security: max-age=15552000; includeSubDomains
< x-content-type-options: nosniff
< x-we-are-hiring: https://toggl.com/jobs/
< x-request-id: a5c3d57bba6a9550f5a0bc6998910123
< via: 1.1 google
< alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
<
* Connection #0 to host desktop.track.toggl.com left intact
```

**Comment by omicron81** [comment]
@kornelijepetak Is there anything else I can do to help figure out the cause of the problem?
